#! /bin/sh

####################################################
#                                                   #
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗    #
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║    #
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║    #
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║    #
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║    #
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝    # 
#####################################################


pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d Home Web Work Chat Music

########## Window Settings ##############
bspc config border_width         2
bspc config window_gap           7
bspc config focus_follows_pointer	true
bspc config split_ratio          0.50 
bspc config borderless_monocle   true
bspc config gapless_monocle      true

########## Border Colors #################
#bspc config focused_border_color "#FFFFFF"
#bspc config normal_border_color "#FFFFFF"

######### Program settings ################
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a Firefox desktop='^2'

######### Other Settings ################
xsetroot -cursor_name left_ptr &
xbacklight -set 30

######## MY picom :) ###################
picom --config ~/.config/picom/picom.conf 

######## THe real beauty behind rice ####
nitrogen --restore &


